[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.21"
clap-verbosity-flag = { version = "3.0.1", features = ["tracing"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
